import turtle
tri = turtle.Turtle()
screen = turtle.Screen()
tri.screen.register_shape("carrot_g2.gif")
tri.screen.register_shape("carrot_g1.gif")
tri.shape("carrot_g2.gif")
tri.color("black")
tri.pu()
t = turtle.Turtle(shape="square")
t.shapesize(4)
t.color("pink")
t.pu()
def drag_handler(x, y):
    #t.ondrag(None)
    #t.onclick(None)
    t.goto(x, y)
    #t.ondrag(drag_handler)
    #t.onclick(drag_handler)
    #tri.hidetutle()
    #tri.shape("circle")
    #tri.shape("carrot_g1.gif")
    #tri.showturtle()
    #tri.shape("carrot_g2.gif")
    #tri.fd(1)
    #tri.bk(1)

#t.ondrag(drag_handler)
screen.onclick(drag_handler)
tri.bk(100)
while tri.distance(t) > 10:
    tri.setheading(tri.towards(t))
    tri.fd(5)
#screen = turtle.Screen()
screen.mainloop()

